apiVersion: v1
kind: Service
metadata:
  name: shop-service
  labels:
    app: dotnet-aks
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dotnet-aks
  type: LoadBalancer
  # env:
  # - name: ConnectionString:ShoppingDB
  #   value: "Server=20.75.211.66,1433;Database=ShopDB;User=sa;Password=BALAJI55!@;TrustServerCertificate=True;"
---
# apiVersion: apps/v1 
# kind: Deployment
# metadata:
#   name: shop-deployment
#   labels:
#     app: aspnet3core
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: aspnet3core
#   template:
#     metadata:
#       labels:
#         app: aspnet3core
#         environment: development
#     spec:
#       containers:
#         - name: aspnet3
#           image: deathstroke45/shoppingapi:latest
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 80
# ---
# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: first-netcore-app
  labels:
    app: dotnet-aks
    component: netcore-app
spec:
  containers:
    - image: deathstroke45/shoppingapi2:latest
      name: webapi
      ports:
        - containerPort: 80
      env: 
        - name: ConnectionString__ShoppingDB
          valueFrom:
            secretKeyRef:
              name: api
              key: connection_string
